name: Go

env: 
  registry: openhackhoe31nr7acr.azurecr.io
  repository: ESnvr/devopshack/apis/trips
  docker_path: apis/trips
  staging_url: https://openhackhoe31nr7trips-staging.azurewebsites.net
  prod_url: https://openhackhoe31nr7trips.azurewebsites.net
  resource_group: openhackhoe31nr7rg
  webapp_name: openhackhoe31nr7trips
  build_name: Trips
  webv_path: apis/trips/webvalidate
  
on:
  push:
    branches: [ master1 ]
    paths: 
    - apis/trips/**
    - .github/workflows/tripsbuild.yml
  pull_request:
    branches: [ master1 ]
    paths: 
    - apis/trips/**
    - .github/workflows/tripsbuild.yml

jobs:

  build_and-test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go get
      
    - name: Test
      run: go test ./tripsgo
      
    - uses: actions/github-script@0.9.0
      if: failure()
      with: 
        github-token: ${{secrets.GITHUB_TOKEN}} 
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
          body: body
          });

