name: Go

on:
  push:
    branches: [ master1 ]
    paths: 
    - apis/trips/**
    - .github/workflows/tripsbuild.yml
  pull_request:
    branches: [ master1 ]
    paths: 
    - apis/trips/**
    - .github/workflows/tripsbuild.yml

jobs:

  build_and-test:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: apis/trips
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go get
      
    - name: Test
      run: go test ./trips/tripsgo/

